version: '3'
services:
  backend:
    build: 
      context: todolist
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app/todolist
    env_file:
      - todolist/.env.local
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d

