FROM golang:1.21-bullseye

WORKDIR /usr/src/app

RUN apt update \
    && apt install -y vim locales \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN localedef -f UTF-8 -i ja_JP ja_JP.utf8

RUN curl -sSf https://atlasgo.sh | sh
RUN go install github.com/google/wire/cmd/wire@v0.5.0
RUN go install entgo.io/ent/cmd/ent@v0.12.3
RUN go install golang.org/x/tools/gopls@v0.13.2
RUN go install github.com/go-delve/delve/cmd/dlv@v1.21.0
RUN go install github.com/josharian/impl@v1.2.0
RUN go install github.com/fatih/gomodifytags@v1.16.0
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2