// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
